//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientMaster
    {
        public int clientMasterId { get; set; }
        public int companyId { get; set; }
        public string contactPersonName { get; set; }
        public string emailId { get; set; }
        public string phoneNo { get; set; }
        public string companyAddress { get; set; }
    
        public virtual companyMaster companyMaster { get; set; }
    }
}
