//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientVendorMaster
    {
        public clientVendorMaster()
        {
            this.requirementVendorMappings = new HashSet<requirementVendorMapping>();
            this.requirmentMasters = new HashSet<requirmentMaster>();
            this.requirmentVendorMappings = new HashSet<requirmentVendorMapping>();
        }
    
        public int clientVendorMaster_Id { get; set; }
        public Nullable<int> userMaster_Id { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual userMaster userMaster { get; set; }
        public virtual ICollection<requirementVendorMapping> requirementVendorMappings { get; set; }
        public virtual ICollection<requirmentMaster> requirmentMasters { get; set; }
        public virtual ICollection<requirmentVendorMapping> requirmentVendorMappings { get; set; }
    }
}
