//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyMaster
    {
        public companyMaster()
        {
            this.clientMasters = new HashSet<clientMaster>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<clientMaster> clientMasters { get; set; }
    }
}
