//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class countryMaster
    {
        public countryMaster()
        {
            this.locationMasters = new HashSet<locationMaster>();
            this.stateMasters = new HashSet<stateMaster>();
        }
    
        public int countryId { get; set; }
        public string countryName { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ICollection<locationMaster> locationMasters { get; set; }
        public virtual ICollection<stateMaster> stateMasters { get; set; }
    }
}
