//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CandidateTrackerEntitiesModel : DbContext
    {
        public CandidateTrackerEntitiesModel()
            : base("name=CandidateTrackerEntitiesModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<candidateMaster> candidateMasters { get; set; }
        public virtual DbSet<candidateSkillMapping> candidateSkillMappings { get; set; }
        public virtual DbSet<cityMaster> cityMasters { get; set; }
        public virtual DbSet<clientVendorMaster> clientVendorMasters { get; set; }
        public virtual DbSet<countryMaster> countryMasters { get; set; }
        public virtual DbSet<locationMaster> locationMasters { get; set; }
        public virtual DbSet<requirementSkillMapping> requirementSkillMappings { get; set; }
        public virtual DbSet<requirementVendorMapping> requirementVendorMappings { get; set; }
        public virtual DbSet<requirmentMaster> requirmentMasters { get; set; }
        public virtual DbSet<requirmentVendorMapping> requirmentVendorMappings { get; set; }
        public virtual DbSet<skillMaster> skillMasters { get; set; }
        public virtual DbSet<stateMaster> stateMasters { get; set; }
        public virtual DbSet<userMaster> userMasters { get; set; }
        public virtual DbSet<userType> userTypes { get; set; }
        public virtual DbSet<clientMaster> clientMasters { get; set; }
        public virtual DbSet<companyMaster> companyMasters { get; set; }
    }
}
