//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class requirmentMaster
    {
        public requirmentMaster()
        {
            this.locationMasters = new HashSet<locationMaster>();
            this.requirementVendorMappings = new HashSet<requirementVendorMapping>();
        }
    
        public int requirment_Id { get; set; }
        public Nullable<int> clientVendorMaster_Id { get; set; }
        public string jobProfileName { get; set; }
        public Nullable<System.DateTime> experienceStartDate { get; set; }
        public Nullable<System.DateTime> experienceEndDate { get; set; }
        public Nullable<int> salaryStartRange { get; set; }
        public Nullable<int> salaryEndRange { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual clientVendorMaster clientVendorMaster { get; set; }
        public virtual ICollection<locationMaster> locationMasters { get; set; }
        public virtual ICollection<requirementVendorMapping> requirementVendorMappings { get; set; }
    }
}
