//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class requirementVendorMapping
    {
        public int requirmentVendorMapping_Id { get; set; }
        public Nullable<int> clientVendorMaster_Id { get; set; }
        public Nullable<int> requirment_Id { get; set; }
        public Nullable<int> candidateId { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual candidateMaster candidateMaster { get; set; }
        public virtual clientVendorMaster clientVendorMaster { get; set; }
        public virtual requirmentMaster requirmentMaster { get; set; }
    }
}
