//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class skillMaster
    {
        public skillMaster()
        {
            this.candidateSkillMappings = new HashSet<candidateSkillMapping>();
            this.requirementSkillMappings = new HashSet<requirementSkillMapping>();
        }
    
        public int skillId { get; set; }
        public string skillName { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ICollection<candidateSkillMapping> candidateSkillMappings { get; set; }
        public virtual ICollection<requirementSkillMapping> requirementSkillMappings { get; set; }
    }
}
