//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class stateMaster
    {
        public stateMaster()
        {
            this.locationMasters = new HashSet<locationMaster>();
        }
    
        public int stateId { get; set; }
        public Nullable<int> countryId { get; set; }
        public string stateName { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual countryMaster countryMaster { get; set; }
        public virtual ICollection<locationMaster> locationMasters { get; set; }
    }
}
