//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class userMaster
    {
        public userMaster()
        {
            this.clientVendorMasters = new HashSet<clientVendorMaster>();
        }
    
        public int userMaster_Id { get; set; }
        public Nullable<int> userType_Id { get; set; }
        public string userName { get; set; }
        public string userAddress { get; set; }
        public string contactNumber { get; set; }
        public string emailId { get; set; }
        public string password { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ICollection<clientVendorMaster> clientVendorMasters { get; set; }
        public virtual userType userType { get; set; }
    }
}
